# Numpy basics

## Install numpy

In [6]:
pip install numpy


[notice] A new release of pip available: 22.3 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


## Importing numpy and array creation

In [7]:
import numpy as np
arr1=np.array([1,2,3,4,5],dtype=np.int32)

In [8]:
arr1

array([1, 2, 3, 4, 5])

## Type of Array

In [9]:
arr1.dtype

dtype('int32')

## 2D Array Creation

In [10]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])

In [11]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## 3D Array 

In [12]:
arr3=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

In [13]:
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

## Array Dimension

In [14]:
arr3.ndim

3

In [15]:
arr=np.array([
    [[1,2,3,4],[5,6,7,8]],
    [[9,10,11,12],[13,14,15,16]]
])

In [16]:
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [17]:
arr.ndim


3

In [18]:
import numpy as np
arr3=np.array([[[1,2,3]]])
print(arr3)
print(arr3.ndim)

[[[1 2 3]]]
3


## Array Shape


In [19]:
arr.shape

(2, 2, 4)

## Array Size

In [20]:
arr.size

16

## 4D Array

In [21]:
arr4=np.array([
    [
        [
            [1,2,3],[4,5,6]
        ]
    ],
    [
        [
            [7,8,9],[10,11,12]
        ]
    ]
])

In [22]:
arr4.ndim

4

## Special Numpy Arrays

## zero array

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## Ones array

In [24]:
import numpy as np
array1=np.ones((3,4))

In [25]:
array1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Empty array

In [26]:
e_array=np.empty((3,4))

In [27]:
e_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Identity array

In [28]:
i_array1=np.identity(3)
i_array1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
i_array2=np.eye(2)
i_array2

array([[1., 0.],
       [0., 1.]])

## Random array

In [30]:
rand_array1=np.random.rand(5)
rand_array1

array([0.01357972, 0.50659758, 0.13120899, 0.98094177, 0.73609108])

In [31]:
rand_array2=np.random.rand(3,4)
rand_array2

array([[0.86852569, 0.84359154, 0.59321254, 0.00570842],
       [0.08681175, 0.36045509, 0.83987859, 0.5083052 ],
       [0.10644627, 0.85683943, 0.07374469, 0.5117372 ]])

## Range array

In [32]:
range_array1=np.arange(10)
range_array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
range_array2=np.arange(5,15,2)
range_array2

array([ 5,  7,  9, 11, 13])

## Boolean array

In [34]:
bool_array=np.array([1,2,3,4,5])
condition=bool_array>3
print(condition)

[False False False  True  True]


## full()

In [35]:
f_array=np.full([2,3],15,dtype=int)
f_array

array([[15, 15, 15],
       [15, 15, 15]])

## linspace()

In [39]:
lin_array1=np.linspace(0,10,5)
lin_array1

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## reshape()

In [37]:
re_array1=np.linspace(10,20,6).reshape(2,3)
re_array1

array([[10., 12., 14.],
       [16., 18., 20.]])

In [38]:
re_array2=np.linspace(10,20,6).reshape(3,3)
re_array2

ValueError: cannot reshape array of size 6 into shape (3,3)

In [ ]:
re_array3=np.linspace(10,20,6).reshape(6,1)
re_array3

## arange() and reshape()

In [ ]:
np.arange(1,20,2).reshape(2,5)

In [ ]:
np.arange(100,300,5).size

In [ ]:
np.arange(100,300,5).reshape(5,8)

## Array arithmetic

In [40]:
arith_array=np.array([25,50,56,58])
arith_array

array([25, 50, 56, 58])

In [41]:
print(arith_array+5)

[30 55 61 63]


In [43]:
print(arith_array-5)

[20 45 51 53]


In [44]:
print(arith_array*2)

[ 50 100 112 116]


In [45]:
print(arith_array/4)

[ 6.25 12.5  14.   14.5 ]


## Indexing and Slicing


### 1D Array

### Indexing / Accessing elements

In [2]:
import numpy as np
ind_array1=np.array([1,2,3,4,5])
print(ind_array1)
print(ind_array1[0])
print(ind_array1[3])

[1 2 3 4 5]
1
4


### Slicing

In [3]:
print(ind_array1[1:4])

[2 3 4]


In [4]:
print(ind_array1[:3])

[1 2 3]


In [5]:
print(ind_array1[2:])

[3 4 5]


### Modifying array elements

In [6]:
mod_array=np.array([10,20,30])
print(mod_array)
mod_array[1]=15
print(mod_array)

[10 20 30]
[10 15 30]


### 2D Array

In [8]:
ind_array2=np.array([[1,2,3],[4,5,6],[7,8,9]])
ind_array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Indexing / Accessing elements

In [9]:
print(ind_array2[0,1])
print(ind_array2[2,2])

2
9


In [10]:
print(ind_array2[1:3,0:2])

[[4 5]
 [7 8]]


In [11]:
ind_array3=np.array([[1,2,3],[4,5,6]])
print(ind_array3[0,1])

2


In [12]:
print(ind_array3[:,1])

[2 5]


In [13]:
print(ind_array3[1,1:])

[5 6]


In [14]:
print(ind_array3[:2,:2])

[[1 2]
 [4 5]]


## Basic Operations


### Array aggregation

In [46]:
#sum
aggr_array=np.array([5,10,15,25])
print(aggr_array.sum())

55


In [48]:
print(aggr_array.sum(axis=0))

55


In [49]:
aggr_array1=np.array([[5,10,15,25]])
print(aggr_array1.sum(axis=1))                   

[55]


In [52]:
aggr_array2=np.array([[5,10,15,25],[10,20,30,40]])
print(aggr_array2.sum())         

155


In [53]:
aggr_array2=np.array([[5,10,15,25],[10,20,30,40]])
print(aggr_array2.sum(axis=0))    

[15 30 45 65]


In [54]:
aggr_array2=np.array([[5,10,15,25],[10,20,30,40]])
print(aggr_array2.sum(axis=1))   

[ 55 100]


In [55]:
#min
print(aggr_array2.min())

5


In [56]:
#max()
print(aggr_array2.max())

40


In [57]:
#mean
print(aggr_array2.mean())

19.375


In [58]:
#Standard deviation
print(aggr_array2.std())

11.02199505534275


### Join

In [15]:
join_array1=np.array([1,2,3])
join_array2=np.array([4,5,6])
join_result=np.concatenate((join_array1,join_array2))
print(join_result)

[1 2 3 4 5 6]


### Search

In [16]:
original_array=np.array([1,2,3,4,5,4,4])
search_item=np.where(original_array==4)
print(search_item)

(array([3, 5, 6], dtype=int64),)


In [17]:
search_item1=np.where(original_array==6)
print(search_item1)

(array([], dtype=int64),)


### Split

In [18]:
array_to_split=np.array([1,2,3,4,5,6])
splitted_array=np.array_split(array_to_split,3)
print(splitted_array)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [19]:
splitted_array=np.array_split(array_to_split,5)
print(splitted_array)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [20]:
splitted_array=np.array_split(array_to_split,6)
print(splitted_array)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [21]:
splitted_array=np.array_split(array_to_split,7)
print(splitted_array)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32)]


### Sort

In [22]:
array_to_sort=np.array([3,2,0,1])
print(np.sort(array_to_sort))

[0 1 2 3]


In [23]:
print(np.sort(array_to_sort,axis=0))

[0 1 2 3]


In [24]:
#in reverse order
sorted_array=np.sort(array_to_sort)
reversed_array=sorted_array[::-1]
print(reversed_array)

[3 2 1 0]


### Sorting - 2D array

In [25]:
array_to_sort1=np.array([[3,2,0,1],[5,2,6,9]])
print(np.sort(array_to_sort1))

[[0 1 2 3]
 [2 5 6 9]]


In [26]:
print(np.sort(array_to_sort1,axis=1))

[[0 1 2 3]
 [2 5 6 9]]


In [27]:
print(np.sort(array_to_sort1,axis=0))

[[3 2 0 1]
 [5 2 6 9]]


In [28]:
array_to_sort1=np.array([[5,10,6,9],[3,20,0,1]])
print(np.sort(array_to_sort1,axis=0))

[[ 3 10  0  1]
 [ 5 20  6  9]]


### Reshape

In [29]:
array_to_reshape=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshaped_array=array_to_reshape.reshape(4,3)
print(reshaped_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Array Broadcasting

In [59]:
broad_array1=np.array([[1,2,3],[4,5,6]])
broad_array2=np.array([10,20,30])
print(broad_array1+broad_array2)

[[11 22 33]
 [14 25 36]]


In [61]:
broad_array3=np.array([[1,2,3],[4,5,6]])
broad_array4=np.array([10,20])
print(broad_array3+broad_array4)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [64]:
broad_array5=np.array([[1,2,3],[4,5,6]])
broad_array6=np.array([[10,20,30],[15,25,35]])
print(broad_array5+broad_array6)

[[11 22 33]
 [19 30 41]]


## Array with Structured Data

In [80]:
struc_array1=np.array([('Sana',20,60.5),('Mansi',21,62.3)],
                      dtype=[('name',(np.str_,10)),('age',np.int32),('weight',np.float64)])

In [72]:
struc_array1

array([('Sana', 20, 60.5), ('Mansi', 21, 62.3)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [73]:
print(struc_array1['name'])

['Sana' 'Mansi']


In [74]:
print(struc_array1['age'])

[20 21]


In [75]:
print(struc_array1['weight'])

[60.5 62.3]


#### Sorting according to 'name'

In [79]:
struc_array2=np.sort(struc_array1,order='name')
print("sorting according to name ",struc_array2)

sorting according to name  [('Mansi', 21, 62.3) ('sana', 20, 60.5)]


## Copy vs View

In [81]:
#copy()
original_array=np.array([1,2,3,4,5])
print("Original array ",original_array)
copy_array=original_array.copy()
original_array[0]=42
print("After updation")
print(original_array)
print(copy_array)

Original array  [1 2 3 4 5]
After updation
[42  2  3  4  5]
[1 2 3 4 5]


In [82]:
#view()
original_array1=np.array([1,2,3,4,5])
print("Original array ",original_array)
view_array=original_array.view()
original_array1[0]=42
print("After updation")
print(original_array1)
print(view_array)

Original array  [42  2  3  4  5]
After updation
[42  2  3  4  5]
[42  2  3  4  5]


## Exercises

1.Create a numpy array with 5 elements consisting of random integers between 1 and 100.

In [1]:
import numpy as np
ran_array=np.random.randint(1,101,size=5)

In [2]:
ran_array

array([77, 69, 79, 66, 68])

2.Create a numpy array containing the numbers from 1 to 10, and
#then reshape it to a 2x5 matrix.


In [3]:
num_array=np.arange(1,11).reshape(2,5)
num_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

3.Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.


In [5]:
num_array2=np.arange(1,21)
print("Original array : ",num_array2)
print("Elements between 5th and 15th index : ")
print(num_array2[5:16])

Original array :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Elements between 5th and 15th index : 
[ 6  7  8  9 10 11 12 13 14 15 16]




4.Create a numpy array with 10 elements consisting of evenly spaced numbers between 0 and 1.


In [6]:
num_array3=np.linspace(0,1,10)
num_array3

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

5.Create a numpy array containing the numbers from 1 to 9, and then square each element in the array.


In [7]:
num_array4=np.arange(1,10)
print("Original_array :",num_array4)
new_array=num_array4**2
print("New array : ",new_array)

Original_array : [1 2 3 4 5 6 7 8 9]
New array :  [ 1  4  9 16 25 36 49 64 81]
