# numpy basics

In [1]:
print("Hii")

Hii


In [2]:
"Hii"

'Hii'

In [2]:
import numpy as np
s1=np.array([[10,20,5],[30,20,15]])
s1

array([[10, 20,  5],
       [30, 20, 15]])

In [4]:
s1.sum()

100

In [5]:
s1.sum(axis=0)

array([40, 40, 20])

In [6]:
s1.sum(axis=1)

array([35, 65])